version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: mainnet-container
    environment:
      POSTGRES_USER: kata
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mainnet-db
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d  
      - postgres-data:/var/lib/postgresql/data

  # this for later
  # redis:
  #   image: redis:latest
  #   container_name: mainnet-redis
  #   ports:
  #     - "6379:6379"

volumes:
  postgres-data: